on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd jhaemin/jhaemin.com-next
            git reset --hard
            git checkout main
            git pull --rebase
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            export BUN_INSTALL=~/.bun
            export PATH=$BUN_INSTALL/bin:$PATH
            bun install
            if bun run typecheck; then
              if bun run build; then
                pm2 start ecosystem.config.cjs
              else
                echo "Build failed"
                exit 1
              fi
            else
              echo "Type check failed"
              exit 1
            fi
